---
components:
  Login Nodes:
    service_aggregator: degrade_any_fail_all
    nagios_services:
      - host: sfec1
        service: SSH
      - host: sfec2
        service: SSH
      - host: sfec3
        service: SSH
  "Tier 1: High Performance Storage":
    service_aggregator: worst
    nagios_services:
      - host: peacock
        service: PANASAS_REALM_STATUS
  "Tier 1: High Performance Storage":
    independent: true # Means it should manage its own incident thread that can happen concurrent with the main incident thread for the component.
    service_aggregator: worst
    nagios_services:
      - host: peacock
        service: PANASAS_RESPONSE_TIME
    current_component_status: true # a ServiceStatusInterface implementation

