---
components:
  Login Nodes:
    service_aggregator: degrade_if_any_fail_if_all
    nagios_services:
      - host: sfec1
        service: SSH
      - host: sfec2
        service: SSH
      - host: sfec3
        service: SSH
  "Tier 1: High Performance Storage":
    service_aggregator: worst
    nagios_services:
      - host: peacock
        service: PANASAS_REALM_STATUS

nagios_api:
  url: https://monitor.my.org/nagios/cgi-bin
  username: abc
  password: def

cachet_api:
  url: http://xxxx.com/api/v1/
  api_key: xxxx
